import {
  Icon1,
  Icon2,
  Icon3,
  Icon4,
  Icon5,
  Icon6,
} from "../../component/UserIcon";

const SwiperDummyData = [
  {
    img: "https://i.imgur.com/fNPu0Hr.jpeg",
    icon: <Icon1 />,
    nickname: "a",
    isHearCliked: true,
    likes: 1,
    tags: ["태그11"],
    comment: "가",
  },
  {
    img: "https://i.imgur.com/JsWOQSb.jpeg",
    icon: <Icon2 />,
    nickname: "ab",
    isHearCliked: false,
    likes: 2,
    tags: ["태그21", "태그22"],
    comment: "가나",
  },
  {
    img: "https://i.imgur.com/sfOjpEM.jpeg",
    icon: <Icon3 />,
    nickname: "abc",
    isHearCliked: true,
    likes: 3,
    tags: ["태그31", "태그32", "태그33"],
    comment: "가나다",
  },
  {
    img: "https://i.imgur.com/oQ6T2Y7.jpeg",
    icon: <Icon4 />,
    nickname: "abcd",
    isHearCliked: false,
    likes: 4,
    tags: ["태그41"],
    comment: "가나다라",
  },
  {
    img: "https://i.imgur.com/Pb4OB5K.jpeg",
    icon: <Icon5 />,
    nickname: "abcde",
    isHearCliked: true,
    likes: 5,
    tags: ["태그51", "태그52"],
    comment: "가나다라마",
  },
  {
    img: "https://i.imgur.com/Qmv3O9W.jpeg",
    icon: <Icon6 />,
    nickname: "abcdef",
    isHearCliked: false,
    likes: 6,
    tags: ["태그61", "태그62", "태그63"],
    comment: "가나다라마바",
  },
  {
    img: "https://i.imgur.com/fnym8NM.jpeg",
    icon: <Icon1 />,
    nickname: "abcdefg",
    isHearCliked: true,
    likes: 7,
    tags: ["태그71"],
    comment: "가나다라마바사",
  },
  {
    img: "https://i.imgur.com/OCCktEm.jpeg",
    icon: <Icon2 />,
    nickname: "abcdefgh",
    isHearCliked: false,
    likes: 8,
    tags: ["태그81", "태그82"],
    comment: "가나다라마바사아",
  },
  {
    img: "https://i.imgur.com/ob8Gq1k.jpeg",
    icon: <Icon3 />,
    nickname: "abcdefghi",
    isHearCliked: true,
    likes: 9,
    tags: ["태그91", "태그92", "태그93"],
    comment: "가나다라마바사아자",
  },
  {
    img: "https://i.imgur.com/Vs9BNjp.jpeg",
    icon: <Icon4 />,
    nickname: "abcdefghij",
    isHearCliked: false,
    likes: 10,
    tags: ["태그101"],
    comment: "가나다라마바사아자차",
  },
];

export default SwiperDummyData;
